{.character = "WOMAN", .text = "Oough! Ahhh!"},
{.character = "SECRET SERVICE AGENT", .text = "Upstairs."},
{.character = "WOMAN", .text = "What's going on? What's the matter? Who are you?"},
{.character = "WOMAN", .text = "Hey!"},
{.character = "WOMAN", .text = "Dade! Dade!"},
{.character = "AGENT", .text = "Knock it down."},
{.character = "PROSECUTOR", .text = "The defendant, Dade Murphy, who calls himself \"Zero Cool\", has repeatedly committed criminal acts of a malicious nature. This defendant possesses a superior intelligence, which he uses to a destructive and antisocial end. His computer virus crashed one thousand five hundred and seven computer systems, including Wall Street trading systems, single handedly causing a seven point drop in the New York Stock Market."},
{.character = "JUDGE", .text = "Dade Murphy, I hereby fine your family forty-five thousand dollars..."},
{.character = "JUDGE", .text = "...and sentence you to probation, under which you are forbidden to own or operate a computer or touch tone telephone, until the day of your eighteenth birthday."},
{.character = "MRS. MURPHY", .text = "Dade?"},
{.character = "DADE", .text = "Yeah, mom?"},
{.character = "MRS. MURPHY", .text = "What are you doing?"},
{.character = "DADE", .text = "I'm taking over a TV network."},
{.character = "MRS. MURPHY", .text = "Finish up, honey, and get to sleep. And happy birthday."},
{.character = "NORM", .text = "Security, uh Norm, Norm speaking."},
{.character = "DADE", .text = "Norman? This is Mr. Eddie Vedder, from Accounting. I just had a power surge here at home that wiped out a file I was working on. Listen, I'm in big trouble, do you know anything about computers?"},
{.character = "NORM", .text = "Uhhmmm... uh gee, uh..."},
{.character = "DADE", .text = "Right, well my BLT drive on my computer just went AWOL, and I've got this big project due tomorrow for Mr. Kawasaki, and if I don't get it in, he's gonna ask me to commit Hari Kari..."},
{.character = "NORM", .text = "Uhhh.. ahahaha..."},
{.character = "DADE", .text = "Yeah, well, you know these Japanese management techniques. Could you, uh, read me the number on the modem?"},
{.character = "NORM", .text = "Uhhhmm..."},
{.character = "DADE", .text = "It's a little boxy thing, Norm, with switches on it... lets my computer talk to the one there..."},
{.character = "NORM", .text = "212-555-4240."},
{.character = "COMMENTATOR", .text = "...so-called American Indians, Latinos and Blacks come from a genetically mediocre stock..."},
{.character = "DADE", .text = "Yak yak yak. Get a job!"},
{.character = "TV", .text = "You are about to experience the awe and mystery, which reaches from the inner mind, to... The Outer Limits."},
{.character = "DADE", .text = "Yesssss!"},
{.character = "DADE", .text = "Hey! What?"},
{.character = "DADE", .text = "No, wait."},
{.character = "DADE", .text = "Unbelievable. A hacker!"},
{.character = "DADE", .text = "Yeah, okay \"Acid Burn\", that's enough."},
{.character = "DADE", .text = "Shit on me!"},
{.character = "MRS. MURPHY", .text = "Good morning. You unpack your stuff yet?"},
{.character = "DADE", .text = "Mm-hmm."},
{.character = "MRS. MURPHY", .text = "Up all night again, huh?"},
{.character = "DADE", .text = "Can this wait until both my eyes are open, please?"},
{.character = "MRS. MURPHY", .text = "Can I cut the electricity to his room so he'll sleep normal hours? He's been playing with his computer all night for a solid week. Well yes, he could be playing with himself. Mmm hmm. Yes I'll ask. Dade, you like girls, don't you?"},
{.character = "DADE", .text = "Well, yeah, I just haven't found one as charming as you yet."},
{.character = "MRS. MURPHY", .text = "You haven't been doing anything stupid, right, Dade? Right, Dade?!"},
{.character = "DADE", .text = "Right, mom. And I'm still a virgin!"},
{.character = "MRS. MURPHY", .text = "You hooked it up to the phone, didn't you? Dade! Turn the shower off! You screw up again and you won't get into college!"},
{.character = "MRS. MURPHY", .text = "I'm sorry we had to move in your senior year. I didn't want to sell the house but I had to take this new job, you know that. You're going to love New York, it's the city that never sleeps!"},
{.character = "DADE", .text = "Excuse me."},
{.character = "KID", .text = "Yo, chill man, I'm talking to Venezuela."},
{.character = "DADE", .text = "Yeah, I'm sorry, I was just looking for the principal's office."},
{.character = "KID", .text = "Sorry, I can't help you, okay?"},
{.character = "GIRL", .text = "Do you have your transfer forms?"},
{.character = "GIRL", .text = "It's a relatively straightforward question."},
{.character = "GIRL", .text = "Do you speak English?"},
{.character = "DADE", .text = "Sorry, you wanted...?"},
{.character = "GIRL", .text = "I wanted transfer forms."},
{.character = "GIRL", .text = "Thank you."},
{.character = "GIRL", .text = "Are you coming?"},
{.character = "GIRL", .text = "The gym is through there, and the cafeteria is through there."},
{.character = "DADE", .text = "Great. Cool. What's your name?"},
{.character = "GIRL", .text = "Kate. Kate Libby."},
{.character = "KATE", .text = "Here's your class."},
{.character = "DADE", .text = "My... class. You mean I'm not in your class?"},
{.character = "KATE", .text = "No, you're not in my class."},
{.character = "DADE", .text = "Give me time!"},
{.character = "GUY", .text = "Hey, you new?"},
{.character = "DADE", .text = "Yeah."},
{.character = "GUY", .text = "Tell him about the pool, Kate."},
{.character = "DADE", .text = "Pool?"},
{.character = "KATE", .text = "Yeah, there's an Olympic size swimming pool up on the roof. Take the stairs over there."},
{.character = "DADE", .text = "Yeah! Sure."},
{.character = "DADE", .text = "Thanks!"},
{.character = "GEEK", .text = "Hey! Hold the door!"},
{.character = "Dade", .text = "No pool."},
{.character = "KATE", .text = "Oh my God! He found the pool."},
{.character = "TEACHER", .text = "I'm Mr. Simpson. And I'm subbing for Ms. Bayliss who was arrested at the anti-fur rally. I know some of you kids got computers at home. But these are school property, people, and I don't want to see any gum stuck to 'em. Chapter 1. Designing graphical interface..."},
{.character = "KID", .text = "So, um, what's your interest in Kate Libby, eh? Academic? Purely sexual?"},
{.character = "DADE", .text = "Homicidal?"},
{.character = "KID", .text = "What's up, man? I'm the Phreak!"},
{.character = "PHREAK", .text = "The Phantom Phreak? The king of Nynex? I know you play the game."},
{.character = "JOEY", .text = "Phreakphreakphreakphreakphreak, dudedudedudedudedudedude... I gotta..."},
{.character = "PHREAK", .text = "Joey, Joey..."},
{.character = "JOEY", .text = "What? whatwhatwhat?"},
{.character = "PHREAK", .text = "One more \"dude\" out of you and I'm gonna slap the shit outa you, okay? Now I'm trying to save you from yourself but you gotta stop letting your mama dress you, man! Check it..."},
{.character = "JOEY", .text = "I need a handle, man. I don't have an identity until I have a handle."},
{.character = "PHREAK", .text = "You know, you're right about that. Check it, Friday."},
{.character = "JOEY", .text = "Alright. How about the Master of Disaster, huh?"},
{.character = "PHREAK", .text = "You're hopeless, man, utterly hopeless."},
{.character = "JOEY", .text = "Ultra Laser. Doctor Doom!"},
{.character = "CEREAL", .text = "Check this out, each and every one of you. Compilation tape, of my own making. I call this the \"Greatest Zooks Album\". Featuring artists like, well I got some Hendrix on there, some Joplin, Mama Cass, Belushi... all great artists that asphyxiated on their own vomit!"},
{.character = "CEREAL", .text = "Can't get this in stores, man, I made it!"},
{.character = "OPERATOR", .text = "Please deposit five dollars for the first minute."},
{.character = "OPERATOR", .text = "Thank you."},
{.character = "PHREAK", .text = "Nonono, thank YOU!"},
{.character = "DADE", .text = "That's a nice score for a girl."},
{.character = "KATE", .text = "Think you can do better?"},
{.character = "DADE", .text = "I'll give it a shot."},
{.character = "CURTIS", .text = "Is this kid bothering you, Kate?"},
{.character = "DADE", .text = "Sorry, can I get some room here?"},
{.character = "CURTIS", .text = "Yeah. Why don't you come up here?"},
{.character = "CURTIS", .text = "He's good!"},
{.character = "DADE", .text = "Well, it looks like I'm on top."},
{.character = "PHREAK", .text = "Congratulations. No one's ever beat her before. You just made an enemy for life. Boy meets world. Let's go?"},
{.character = "DADE", .text = "Who's that?"},
{.character = "PHREAK", .text = "Curtis."},
{.character = "DADE", .text = "And what's he do?"},
{.character = "PHREAK", .text = "That's it, you're looking at it, he just looks slick all day."},
{.character = "PHREAK", .text = "What's up?"},
{.character = "PHREAK", .text = ""},
{.character = "PHREAK", .text = "Way cool! You saw that?"},
{.character = "KATE", .text = "What the hell is going on?"},
{.character = "DADE", .text = "Pool on the roof must have a leak."},
{.character = "PHREAK", .text = "Man, oh man, this is gonna be good."},
{.character = "KATE", .text = "If God gave men brains bigger than dogs', they wouldn't hump womens' legs at cocktail parties."},
{.character = "KATE", .text = "Ruth Libby."},
{.character = "TEACHER", .text = "I'm not so sure your mother qualifies as a significant author of the twentieth century."},
{.character = "KATE", .text = "Her last book sold two million copies."},
{.character = "CLASS", .text = "Woooooo!"},
{.character = "TEACHER", .text = "\"Angel-headed hipsters burning for the ancient heavenly connection to the starry dynamo in the machinery of the night.\""},
{.character = "DADE", .text = "That's Ginsburg."},
{.character = "TEACHER", .text = "Nice. Very nice."},
{.character = "KATE", .text = "He's not in this class."},
{.character = "DADE", .text = "I said give me time."},
{.character = "KATE", .text = "He's not enrolled in this class."},
{.character = "TEACHER", .text = "Well, he's on my list."},
{.character = "TEACHER", .text = "\"Of all the things I've lost, I miss my mind the most?\""},
{.character = "CEREAL", .text = "Ozzy Osbourne!"},
{.character = "TEACHER", .text = "You. What is your name?"},
{.character = "CEREAL", .text = "Uh, Emmanuel Goldstein, sir?"},
{.character = "TEACHER", .text = "You, however, are not on my list."},
{.character = "CEREAL", .text = "Whoa, this isn't wood shop class?"},
{.character = "MRS. MURPHY", .text = "How was school?"},
{.character = "DADE", .text = "Hmmm."},
{.character = "MRS. MURPHY", .text = "What did we learn in school today?"},
{.character = "DADE", .text = "Revenge."},
{.character = "MRS. MURPHY", .text = "Aaaah. Did we meet someone special?"},
{.character = "DADE", .text = "No. No one special."},
{.character = "MRS. MURPHY", .text = "Okay, I gotta get back to work. I'm gonna be home late.  And would you try and please fill these out?"},
{.character = "MRS. MURPHY", .text = "Oh don't worry, it's only the rest of your life."},
{.character = "DADE", .text = "Right. Anything else, you want me to mow the lawn? Oops, forgot. New York. No grass."},
{.character = "MRS. MURPHY", .text = "And unpack."},
{.character = "CEREAL", .text = "FYI, alright man, you can sit at home, and do like absolutely nothing and..."},
{.character = "CEREAL", .text = "...and your name goes through like seventeen computers a day. 1984, yeah right man, that's a typo. Orwell's here and now, he's living large. We have no names, man, no names. We are nameless. Can I score a fry? Thanks."},
{.character = "PHREAK", .text = "Meet Cereal Killer. As in Froot Loops? But he does know things."},
{.character = "JOEY", .text = "Anyways, guys, guys, listen, listen to me. I'm in this computer right? So I'm looking around..."},
{.character = "PHREAK", .text = "D'you bring those Crayola books?"},
{.character = "CEREAL", .text = "Oh yeah, technicolor rainbow."},
{.character = "CEREAL", .text = "Green one."},
{.character = "JOEY", .text = "What is that, what is that? Lemmie see. What are these?"},
{.character = "DADE", .text = "International Unix Environments."},
{.character = "CEREAL", .text = "Luscious orange?"},
{.character = "DADE", .text = "Computer security criteria, DOD standards."},
{.character = "DADE", .text = "The Pink Shirt Book, Guide to IBM PCs. So called due to the nasty pink shirt the guy wears on the cover."},
{.character = "CEREAL", .text = "What's that?"},
{.character = "DADE", .text = "Devil book. The Unix Bible."},
{.character = "CEREAL", .text = "What's that?"},
{.character = "DADE", .text = "Dragon book. Compiler design."},
{.character = "CEREAL", .text = "Oh yeah? What's that?"},
{.character = "DADE", .text = "The Red Book. NSA Trusted Networks. Otherwise known as the Ugly Red Book that won't fit on a shelf."},
{.character = "JOEY", .text = "Anyway, anyway, guys guys guys, come on. I'm in this computer, right. So I'm looking around, looking around, you know, throwing commands at it, I don't know where it is or what it does or anything. It's like, it's like choice, it's just beautiful, okay. Like four hours I'm just messing around in there. Finally I figure out, that it's a bank. Right, okay wait, okay, so it's a bank. So, this morning, I look in the paper, some cash machine in like Bumsville Idaho, spits out seven hundred dollars into the middle of the street."},
{.character = "CEREAL", .text = "That's kinda cool."},
{.character = "JOEY", .text = "That was me. That was me. I did that."},
{.character = "DADE", .text = "You did this from your house."},
{.character = "PHREAK", .text = "What are you, stoned or stupid? You don't hack a bank across state lines from your house, you'll get nailed by the FBI. Where are your brains, in your ass? Don't you know anything?"},
{.character = "CEREAL", .text = "Stupid, man. It's universally stupid."},
{.character = "JOEY", .text = "You guys always think I should know everything, and you never tell me anything. Am I right?"},
{.character = "PHREAK", .text = "Alright, what are the three most commonly used passwords?"},
{.character = "JOEY", .text = "Love, secret, and uh, sex.  But not in that order, necessarily, right?"},
{.character = "CEREAL", .text = "Yeah but don't forget God. System operators love to use God. It's that whole male ego thing."},
{.character = "PHREAK", .text = "Look, you wanna be elite? You gotta do a righteous hack. None of this accidental shit."},
{.character = "CEREAL", .text = "Oh yeah, you want a seriously righteous hack, you score one of those Gibsons man. You know, supercomputers they use to like, do physics, and look for oil and stuff?"},
{.character = "PHREAK", .text = "Ain't no way, man, security's too tight. The big iron?"},
{.character = "DADE", .text = "Maybe. But, if I were gonna hack some heavy metal, I'd, uh, work my way back through some low security, and try the back door."},
{.character = "own nipples in mock sexual", .text = "Yeah but oh man, wouldn't you just love to get one of those Gibsons, baby? Ooooh!"},
{.character = "PHREAK", .text = "Yo, who ate all of my fries?"},
{.character = "CEREAL", .text = "Joey?!"},
{.character = "JOEY", .text = "What, no, nonononono, I didn't touch your fries. I did not touch your fries."},
{.character = "PHREAK", .text = "Cereal, man, you owe me a pack."},
{.character = "CEREAL", .text = "It was him, man!"},
{.character = "PHREAK", .text = "You're psyched. You need to lay off of that shit."},
{.character = "CEREAL", .text = "I'm gonna hit you!"},
{.character = "JOEY", .text = "YES! Home run, home run. You and me Lucy. We're gonna show em baby."},
{.character = "HAL", .text = "Mr. Belford?"},
{.character = "PLAGUE", .text = "My name is the Plague."},
{.character = "HAL", .text = "Uh, Mr. The Plague, uh, something weird's happening on the net."},
{.character = "PLAGUE", .text = "As in what, you hapless techno-weenie?"},
{.character = "HAL", .text = "Uh, the accounting subdirectory in the Gibson is working really hard. We got one person online, the workload is enough for like ten users. I think we've got a hacker."},
{.character = "JOEY", .text = "Okay, okay, we need proof that we were here. Right, uh..."},
{.character = "JOEY", .text = "Yeah, Garbage, okay, give me Garbage."},
{.character = "PLAGUE", .text = "Never fear. I is here."},
{.character = "HAL", .text = "I've narrowed the activity to terminal 23."},
{.character = "PLAGUE", .text = "Let's echo 23, see what's up."},
{.character = "PLAGUE", .text = "\"God\" wouldn't be up this late."},
{.character = "PLAGUE", .text = "Shit! Get me the switching control center."},
{.character = "PLAGUE", .text = "I need to trace a call that's in progress."},
{.character = "JOEY", .text = "Shit! Uh yeah... hold on, mom. Hold on one second."},
{.character = "JOEY'S MOM", .text = "I mean it! Open the door, Joseph."},
{.character = "JOEY", .text = "Yeah, uh, yeah, okay."},
{.character = "JOEY", .text = "There you go."},
{.character = "JOEY'S MOM", .text = "Bed. Sleep. Now!"},
{.character = "JOEY'S MOM", .text = "Sweet dreams, Joey."},
{.character = "HAL", .text = "He's gone!"},
{.character = "PLAGUE", .text = "Did you get a trace?"},
{.character = "OPERATOR", .text = "Yeah, we got him."},
{.character = "PLAGUE", .text = "Good."},
{.character = "CEREAL", .text = "Nice place, huh."},
{.character = "DADE", .text = "You heard of a hacker called Acid Burn? You know who he is?"},
{.character = "PHREAK", .text = "No, don't know who he is. Do you?"},
{.character = "PHREAK", .text = "Nikon! Lord Nikon this is..."},
{.character = "DADE", .text = "Crash Override."},
{.character = "NIKON", .text = "Never heard of you. Done anything?"},
{.character = "DADE", .text = "No."},
{.character = "PHREAK", .text = "Come on!"},
{.character = "NIKON", .text = "What, your mom buy you a 'Puter for Christmas? Does he know anything?"},
{.character = "PHREAK", .text = "Sure man, he's elite."},
{.character = "NIKON", .text = "Come in."},
{.character = "CEREAL", .text = "Uh... Nikon, can I... can I crash at your place tonight?"},
{.character = "NIKON", .text = "Again? Yeah sure."},
{.character = "BOTH", .text = "Ooka-pow!"},
{.character = "GILL", .text = "Hackers penetrate and ravage delicate public and privately owned computer systems, infecting them with viruses, and stealing materials for their own ends. These people, they are terrorists."},
{.character = "CEREAL", .text = "Agent Richard Gill, You're hacker enemy number one, man. You're a boner!"},
{.character = "NIKON", .text = "Yo, showtime, showtime!"},
{.character = "DADE", .text = "What's going on?"},
{.character = "ALL BUT DADE", .text = "4...3...2...1..."},
{.character = "RAZOR", .text = "Welcome to our show!"},
{.character = "BLADE", .text = "Hack the Planet!"},
{.character = "ALL BUT DADE", .text = "Hack the Planet!"},
{.character = "RAZOR", .text = "For those late night hacks..."},
{.character = "BLADE", .text = "Jolt Cola! The soft drink of the elite hacker."},
{.character = "DADE", .text = "Who are these guys?"},
{.character = "NIKON", .text = "That's Razor and Blade."},
{.character = "DADE", .text = "Razor and Blade."},
{.character = "RAZOR", .text = "That's right, this IS a payphone."},
{.character = "RAZOR AND BLADE", .text = "Don't ask."},
{.character = "BLADE", .text = "As you can see, this is just a simple microcassette recorder. (shows the microcassette recorder)  Hook it up to the phone and drop in five bucks in quarters."},
{.character = "RAZOR", .text = "Record the tones that the coins make. And hang up and get your money back!"},
{.character = "BLADE", .text = "And never again have to pay for a service that would be dirt cheap..."},
{.character = "RAZOR", .text = "...IF it weren't run by a bunch of profiteering gluttons!"},
{.character = "BLADE", .text = "Remember, hacking is more than just a crime. It's a survival trait!"},
{.character = "SS AGENT", .text = "FREEZE!"},
{.character = "JOEY", .text = "What? What? What did I do? What?"},
{.character = "JOEY'S MOM", .text = "Joey!"},
{.character = "AGENT", .text = "Get in there! Sit down!"},
{.character = "ANOTHER AGENT", .text = "Stay down there. Don't move."},
{.character = "JOEY", .text = "Lucy!"},
{.character = "JOEY'S MOM", .text = "JOEY!!!"},
{.character = "GILL", .text = "How's it going, Ray?"},
{.character = "AGENT RAY", .text = "It looks good, sir. We've got an uncorrupted hard drive."},
{.character = "GILL", .text = "In English, please. I didn't spend ten years protecting the president so I could finish my career feeling like an idiot."},
{.character = "AGENT RAY", .text = "I'm sorry, sir. We caught him by surprise, so we don't think he had time to erase his computer files."},
{.character = "GILL", .text = "Good. Good man. Alright, let's finish up here, and take him in for interrogation."},
{.character = "AGENT RAY", .text = "Alright sir."},
{.character = "REPORTER", .text = "Agent Gill, can you spare a moment of your time?"},
{.character = "GILL", .text = "Why of course, Jennifer."},
{.character = "JOEY'S MOM", .text = "Joey!"},
{.character = "JOEY", .text = "Mom..."},
{.character = "JENNIFER", .text = "Just how dangerous are hackers?"},
{.character = "GILL", .text = "Well, hackers penetrate and ravage delicate public and privately owned computer systems, infecting them with viruses..."},
{.character = "JOEY'S MOM", .text = "Joey!"},
{.character = "GILL", .text = "...and stealing sensitive materials for their own ends. These people, they're terrorists..."},
{.character = "JOEY'S MOM", .text = "Joey!"},
{.character = "MARGO", .text = "Good morning, Gentlemen. Please be seated. I see we're still dressing in the dark, Eugene."},
{.character = "PLAGUE", .text = "Once again, don't call me Eugene. A recent unknown intruder penetrated, using a superuser acount, giving him access to our whole system."},
{.character = "MARGO", .text = "Precisely what you're paid to prevent."},
{.character = "PLAGUE", .text = "Someone didn't bother reading my carefully prepared memo on commonly used passwords. Now, as I so meticulously pointed out, the for most used passwords are love, sex, secret and... ...God. So would your holiness care to change her password?"},
{.character = "PLAGUE", .text = "A hacker planted the virus."},
{.character = "MARGO", .text = "Virus?"},
{.character = "PLAGUE", .text = "Yesterday, the ballast program for a supertanker training model mistakenly thought the vessel was empty, and flooded its tanks."},
{.character = "MARGO", .text = "Excuse me?"},
{.character = "PLAGUE", .text = "The little boat flipped over. A virus planted in the Gibson computer system claimed responsibility."},
{.character = "MARGO", .text = "What, it left a note?"},
{.character = "VIRUS", .text = "Unless five million dollars are transferred to the following numbered account in seven days, I will capsize five tankers in the Ellingson fleet."},
{.character = "BOARD MEMBER", .text = "Is that..."},
{.character = "PLAGUE", .text = "That is the virus. Leonardo da Vinci. The problem is we have twenty six ships at sea and we don't know which ones are infected."},
{.character = "DUKE ELLINGSON", .text = "Well then, put the ships' ballasts under manual control."},
{.character = "PLAGUE", .text = "There's no such thing anymore, Duke. These ships are totally computerized. They rely on satellite navigation, which links them to our network, and the virus, wherever they are in the world."},
{.character = "MARGO", .text = "So what are we supposed to do?"},
{.character = "PLAGUE", .text = "Well luckily, you have a gifted and talented security officer. I traced the hacker's call. The secret service picked him up this morning. I'll just search his files for the original virus code, and then I can eliminate it."},
{.character = "SUIT #1", .text = "Now look, now we expect you to get onto this right away, yeah?"},
{.character = "PLAGUE", .text = "Yeah!"},
{.character = "SUIT #1", .text = "Well, how soon?"},
{.character = "PLAGUE", .text = "Well, we're working on it as fast as we can. This is a very common occurrence in corporations as large as ours. You have nothing to worry about."},
{.character = "SUIT #2", .text = "Yeah, right."},
{.character = "SUIT #1", .text = "Now, you're sure about that, Mr. The Plague?"},
{.character = "PLAGUE", .text = "Yeah, the Secret Service is helping us out 100 percent. Okay?"},
{.character = "SUIT #2", .text = "Yeah."},
{.character = "SUIT #1", .text = "Okay."},
{.character = "PLAGUE", .text = "We'll be in touch. Talk to you later."},
{.character = "MARGO", .text = "What the hell was that all about?"},
{.character = "PLAGUE", .text = "I had to move fast. The hacker copied my garbage file."},
{.character = "MARGO", .text = "What?"},
{.character = "PLAGUE", .text = "I created Mister da Vinci so we could call in the Secret Service. So they'd arrest the hacker, sieze his equipment, things that we can't do on our own."},
{.character = "MARGO", .text = "I don't want to go to jail for this."},
{.character = "PLAGUE", .text = "Relax. Think about the 25 million dollars."},
{.character = "MARGO", .text = "But you've created a virus that's going to cause a worldwide ecological disaster, just to arrest some hacker kid?"},
{.character = "PLAGUE", .text = "Basically, uhmm, yeah. Mmm hmmm."},
{.character = "MARGO", .text = "Jesus. You know, you're sick, Eugene. You..."},
{.character = "PLAGUE", .text = "Sh, sh sh sh sh."},
{.character = "PLAGUE", .text = "I'll take care of this."},
{.character = "SECRETARY", .text = "Alright, sir."},
{.character = "PLAGUE", .text = "I can cancel it any time. I don't need any program code. But it's the perfect cover, to confiscate the disc and find out how much of that garbage file has been copied."},
{.character = "MARGO", .text = "Get it! Why did I ever trust you? Get the file. Otherwise you'll lose all your toys."},
{.character = "GILL", .text = "Did you find the program for the virus on any of the discs we confiscated?"},
{.character = "PLAGUE", .text = "No. He's either very smart or very stupid."},
{.character = "GILL", .text = "Then he stashed it somewhere, or he has an accomplice. We'll release him until his indictment, keep tight surveillance, and see if he leads us to your disc."},
{.character = "SECRET SERVICE AGENT BOB", .text = "Unit 3 outside suspect Joey Pardella's apartment. Nothing to report. Suspect still grounded... by his mother."},
{.character = "AGENT BOB", .text = "Listen to this bullshit. \"This is our world now. The world of the electron and the switch, the beauty of the baud. We exist without nationality, skin color, or religious bias. You wage wars, murder, cheat, lie to us and try to make us believe it's for our own good, yet we're the criminals. Yes, I am a criminal. My crime is that of curiosity. I am a hacker and this is my manifesto.\" Huh, right, manifesto? \"You may stop me, but you can't stop us all.\""},
{.character = "AGENT RAY", .text = "Now that's cool."},
{.character = "AGENT BOB", .text = "Cool?"},
{.character = "AGENT RAY", .text = "Yeah, cool."},
{.character = "AGENT BOB", .text = "You think it's cool?"},
{.character = "AGENT RAY", .text = "It's cool!"},
{.character = "AGENT BOB", .text = "It's not cool. It's commie bullshit!"},
{.character = "CEREAL", .text = "So what do you think, can I crash at your place tonight?"},
{.character = "DADE", .text = "What is it with this guy?"},
{.character = "PHREAK", .text = "His parents missed Woodstock and he's been making up for it since. Hey, you hear about Joey's bust?"},
{.character = "CEREAL", .text = "Yeah. Probably had something to do with that bank in Idaho."},
{.character = "PHREAK", .text = "Do you think he could hack a Gibson?"},
{.character = "DADE", .text = "Did you talk to him?"},
{.character = "PHREAK", .text = "Nope. His mom said he's grounded for his next three lifetimes. He isn't to consort with his computer friends. The secret service is really out to get him. Hey there's a big party tonight, you wanna go?"},
{.character = "PHREAK", .text = "It's at Kate's..."},
{.character = "PHREAK", .text = "Thought so!"},
{.character = "GILL", .text = "What the hell are you doing? Plague!"},
{.character = "GILL", .text = "PLAGUE!"},
{.character = "PLAGUE", .text = "Gill."},
{.character = "GILL", .text = "I think we've got something."},
{.character = "PLAGUE", .text = "Uuugh, hard copy."},
{.character = "PLAGUE", .text = "Dade Murphy."},
{.character = "AGENT RAY", .text = "Secret Service!"},
{.character = "AGENT BOB", .text = "Don't move!"},
{.character = "DADE", .text = "Christ! What is the..."},
{.character = "AGENT BOB", .text = "Shut up!"},
{.character = "DADE", .text = "What are you doing, man? Get off me!"},
{.character = "AGENT BOB", .text = ""},
{.character = "PLAGUE", .text = "The year was 1988.  And this nasty virus crashed fifteen hundred systems in one day."},
{.character = "DADE", .text = "Fifteen hundred and seven."},
{.character = "AGENT RAY", .text = "Wow, huh!"},
{.character = "GILL", .text = "It got you seven years probation. No computer, couldn't even use a touch tone phone."},
{.character = "PLAGUE", .text = "Must have been hell, huh? Zero Cool? A virus has been planted in the Ellingson Mineral computer system. You were our prime suspect, till we trashed your stuff and found no trace of it."},
{.character = "GILL", .text = "However, we have come to believe that one Joey Pardella is involved in this Ellingson virus. He or perhaps his accomplice has a disk that Mr. Belford needs to disable that virus. We want you to help us find it."},
{.character = "PLAGUE", .text = "Gill."},
{.character = "PLAGUE", .text = "Loser. I can't believe you were only eleven when you wrote this. It's quite an impressive virus. Dade, I know how you might feel about narking on your friends, but, we're hackers. For us, there's no such thing as family and friends. We're each our own country, with temporary allies and enemies. I'd like to make a treaty with you."},
{.character = "DADE", .text = "I'm sorry. Who are you?"},
{.character = "PLAGUE", .text = "I'm the one who understands you. Now, can we be allies?"},
{.character = "DADE", .text = "Nah. I don't play well with others."},
{.character = "DADE", .text = "Shit! Come on!"},
{.character = "PLAGUE", .text = "Watch which friends you do play with. A record like yours could land you in jail, get you kicked out of school, no colleges would take you. No future. Exiled from everyone and everything you love."},
{.character = "PLAGUE", .text = "I'll be in touch."},
{.character = "PLAGUE", .text = "I'm fine. Oh, and Dade, try to stay out of trouble, okay?"},
{.character = "DADE", .text = "Blow me."},
{.character = "PLAGUE", .text = "Thank you!"},
{.character = "PHREAK", .text = "Her mom makes big bucks writing self-help books for women. Stuff like \"Women Who Love Men Who Are Emotional Amoebae\""},
{.character = "DADE", .text = "That explains a lot."},
{.character = "PHREAK", .text = "Yo, what's up Nikon!"},
{.character = "NIKON", .text = "Yo Phreak! Dade, man, you made it. Houston, we have liftoff, 3 o'clock, check it... don't look right away, what's wrong with you! Look at her man..."},
{.character = "NIKON", .text = "Look out, man. Lisa Blair, 26 East 7th St., apartment 16, 555-4817, BOOM!"},
{.character = "DADE", .text = "How did you know that?"},
{.character = "NIKON", .text = "I got photographic memory. It's a curse! Lisa!"},
{.character = "LISA", .text = "Hey, how do you know my name?"},
{.character = "CEREAL", .text = "Oooo, look at that pooper man. Spandex, it's a privilege, not a right!"},
{.character = "VICKIE", .text = "Hi, my name is Vickie, and I'm an addict."},
{.character = "HANK", .text = "Hi, my name is Hank, and uh, I'm an addict."},
{.character = "JOEY", .text = "Uh, my name's Joey but, uh, I'm not an addict."},
{.character = "JOEY", .text = "Nono, really, really, listen, listen to this. I got in trouble with my computer, right, okay, and my lawyer told the judge that I'm an addict, but I'm not addicted to my computer! No really, really,"},
{.character = "JOEY", .text = "I'm not an addict. I'm not, I'm not."},
{.character = "JOEY", .text = "Can I get some more coffee?"},
{.character = "PHREAK", .text = "Yo. Check this out guys, this is insanely great, it's got a 28.8 BPS modem!"},
{.character = "DADE", .text = "Yeah? Display?"},
{.character = "CEREAL", .text = "Active matrix, man. A million psychedelic colors. Man, baby, sweet, ooo!"},
{.character = "NIKON", .text = "I want it."},
{.character = "PHREAK", .text = "I want it to have my children!"},
{.character = "CEREAL", .text = "Yeah, I bet it looks crispy in the dark."},
{.character = "PHREAK", .text = "Yo, hit the lights."},
{.character = "DADE", .text = "Shit!"},
{.character = "CEREAL", .text = "Shh!"},
{.character = "DADE", .text = "Was that her top?"},
{.character = "PHREAK", .text = "One-handed!"},
{.character = "CEREAL", .text = "Difficulty rating?"},
{.character = "NIKON", .text = "Seven. Wow! Burn's wetware matches her software!"},
{.character = "DADE", .text = "Burn!"},
{.character = "NIKON", .text = "What the f..."},
{.character = "KATE", .text = "Hey! What are you guys doing in here?"},
{.character = "PHREAK", .text = "I'm sorry, we're sorry, just checking out your fly laptop!"},
{.character = "NIKON", .text = "Yeah, it's hyped, you know... you're in the butter zone now, baby."},
{.character = "PHREAK", .text = "Uh-huh!"},
{.character = "KATE", .text = "Yeah, it is... I wanna triple the RAM..."},
{.character = "CURTIS", .text = "Oooh, Leopard Boy... AND the Decepticons. Uh, Kate, Kate, you're not going into that computer shit now, right?"},
{.character = "CURTIS", .text = "Humm, yeah."},
{.character = "CEREAL", .text = "Right."},
{.character = "DADE", .text = "The sensitive type."},
{.character = "KATE", .text = "What is he doing in here?"},
{.character = "PHREAK", .text = "Relax, Burn, he's my guest."},
{.character = "DADE", .text = "Burn. You're Acid Burn. You booted me out of OTV!"},
{.character = "KATE", .text = "What?"},
{.character = "DADE", .text = "I'm Crash Override."},
{.character = "KATE", .text = "You're the moron that's been invading my turf?"},
{.character = "CEREAL", .text = "Whoa, whowhowhowhoa. Crash... and Burn!"},
{.character = "MARGO", .text = "Murphy kid turn you down?"},
{.character = "PLAGUE", .text = "I disguised myself as an Alabama State Trooper and penetrated the FBI NCIC."},
{.character = "MARGO", .text = "Pervert! What are you talking about?"},
{.character = "PLAGUE", .text = "The FBI computer holds files on twenty million Americans.  I just hacked into it."},
{.character = "MARGO", .text = "Congratulations."},
{.character = "PLAGUE", .text = "From here I got access to every piece of data ever stored on Dade Murphy's parents. His parents separated five years ago, reconciled two years later, filed for divorce last year, custody battle, boy chose to go with his mother. Hmm."},
{.character = "MARGO", .text = "So?"},
{.character = "PLAGUE", .text = "So, we get the mother, we get the boy."},
{.character = "KATE", .text = "What the hell are you doing?"},
{.character = "DADE", .text = "It's cool, I'm just looking."},
{.character = "KATE", .text = "It's too much machine for you."},
{.character = "DADE", .text = "Yeah?"},
{.character = "KATE", .text = "I hope you don't screw like you type."},
{.character = "DADE", .text = "It has a killer refresh rate."},
{.character = "KATE", .text = "P6 chip. Triple the speed of the Pentium."},
{.character = "DADE", .text = "Yeah. It's not just the chip, it has a PCI bus. But you knew that."},
{.character = "KATE", .text = "Indeed. RISC architecture is gonna change everything."},
{.character = "DADE", .text = "Yeah. RISC is good."},
{.character = "DADE", .text = "You sure this sweet machine's not going to waste?"},
{.character = "KATE", .text = "Crash Override. What was it. \"Mess with the Best, Die Like the Rest?\""},
{.character = "DADE", .text = "Yeah."},
{.character = "KATE", .text = "Are you challenging me?"},
{.character = "DADE", .text = "Name your stakes."},
{.character = "KATE", .text = "If I win, you become my slave."},
{.character = "DADE", .text = "Your slave?"},
{.character = "KATE", .text = "You wish. You'll do shit work, scan, crack copyrights, whatever I want."},
{.character = "DADE", .text = "And if I win?"},
{.character = "KATE", .text = "Make it my first born."},
{.character = "DADE", .text = "Make it our first date."},
{.character = "KATE", .text = "You're not gonna win."},
{.character = "DADE", .text = "And you have to smile."},
{.character = "KATE", .text = "I don't do dates. But I don't lose either, so you're on."},
{.character = "PHREAK", .text = "So here's the deal. The chosen contest: To hassle Secret Service Agent Richard Gill, and get one back for Joey."},
{.character = "NIKON", .text = "Our decisions are final, by a vote of 2 to 1. No appeals."},
{.character = "CEREAL", .text = "The duel will last until we declare a winner."},
{.character = "PHREAK", .text = "Use only the dialups, access codes and passwords in your collection. Can't ask for any help from us."},
{.character = "DADE", .text = "Talking to me?"},
{.character = "PHREAK", .text = "Any questions?"},
{.character = "KATE", .text = "Yeah. Whose gonna notify his next of kin?"},
{.character = "KATE", .text = "Alright, he's in the personal ads. \"Disappointed white male, crossdresser, looking for discreet friend to bring dreams to reality. Leather, lace, and water sports. Transvestites welcome.\""},
{.character = "GILL", .text = "I... I... I know where you can stick it... I know where you can stick it..."},
{.character = "CALLER", .text = "...wanna lick your earlobes... I wanna lick your lips... I wanna lick your toes... I wanna lick your ankles..."},
{.character = "GILL", .text = "Awww, yeah, you wanna lick something? Lick this."},
{.character = "CALLER", .text = "That's why they call me Stallion..."},
{.character = "GILL", .text = "Aw, that's disgusting!"},
{.character = "CALLER", .text = "My heart is steaming for you..."},
{.character = "CALLER", .text = "...spank you with my..."},
{.character = "GILL", .text = "Aww, Spank your ass..."},
{.character = "PLAGUE", .text = "Animal!"},
{.character = "GILL", .text = "Hey! Hey, ow! Do you know who I am? Do you know who I am?"},
{.character = "EMPLOYEE", .text = "This is accounting, sir. You enquired about an employee of ours, an Agent Richard Gill?"},
{.character = "GILL", .text = "Yes."},
{.character = "EMPLOYEE", .text = "Our records indicate he's deceased."},
{.character = "GILL", .text = "I'm what?"},
{.character = "DADE", .text = "Dead."},
{.character = "PHREAK", .text = "Dead?"},
{.character = "DADE", .text = "Yeah. Like Rigor Mortis, Habeas Corpus."},
{.character = "NIKON", .text = "Very impressive."},
{.character = "CEREAL", .text = "Super hero like even."},
{.character = "KATE", .text = "Yeah, whatever. What's the score?"},
{.character = "PHREAK", .text = "Tie."},
{.character = "PHREAK", .text = "Due to Mr. Gill's untimely demise and everything, I guess you two will have to improvise the next round."},
{.character = "DADE", .text = "Right. If I win, you wear a dress on our date."},
{.character = "KATE", .text = "And if I win, so do you."},
{.character = "DADE", .text = "Deal."},
{.character = "KATE", .text = "Oooohhhh..."},
{.character = "KATE", .text = "Dade. I didn't know your size, so I guessed."},
{.character = "KATE", .text = "You are man enough to stick with the deal, aren't you?"},
{.character = "DADE", .text = "Thanks."},
{.character = "PLAGUE", .text = "You wanted to know who I am, Zero Cool? Well let me explain the New World Order. Governments and corporations need people like you and me. We are samurai. The keyboard cowboys. And all those other people out there who have no idea what's going on are the cattle. Mooo! I need your help, you need my help. Let me help you earn your spurs. Ahh, think about it. Enjoy the laptop, \"Cool\"! Tell me where the disk is."},
{.character = "JOEY'S MOM", .text = "You look pitiful. Okay, okay, you're not grounded anymore."},
{.character = "PHREAK", .text = "Yo, what's up?"},
{.character = "JOEY", .text = "Dude dude dude, I gotta talk to you a minute, listen listen listen. I copied a garbage file from..."},
{.character = "PHREAK", .text = "Big deal. A garbage file's got shit in it, Joey, come on."},
{.character = "JOEY", .text = "Nono, it's like hot or something. I don't know."},
{.character = "PHREAK", .text = "Joey, a garbage file holds miscellaneous data. Junk. Bits of stuff that's been erased, man."},
{.character = "JOEY", .text = "I copied it from Ellingson, okay? They're asking me about it, alright? Will you take a look for me?"},
{.character = "PHREAK", .text = "Oh shit, Joey, you've got a tail."},
{.character = "JOEY", .text = "Shit!"},
{.character = "GILL", .text = "I'm watching you..."},
{.character = "PHREAK'S MOM", .text = "Ramon? Wake up. Ramon! Wake up! Vamano. Time for school, come on."},
{.character = "AGENT", .text = "Secret Service, don't move!"},
{.character = "PHREAK", .text = "Deja vu!"},
{.character = "AGENT BOB", .text = "Ray Sanchez, you are under arrest, under the Computer Fraud and Abuse Act of 1986."},
{.character = "PHREAK", .text = "What are you waiting for, arrest me already!"},
{.character = "COP", .text = "You get one call. Uno. Understand?"},
{.character = "OPERATOR", .text = "Hello, operator services."},
{.character = "PHREAK", .text = "Hello, operator? I'm having trouble dialing a number."},
{.character = "OPERATOR", .text = "What number please?"},
{.character = "PHREAK", .text = "555-4202."},
{.character = "OPERATOR", .text = "Just one moment."},
{.character = "PHREAK", .text = "Thank you."},
{.character = "KATE", .text = "Hello?"},
{.character = "PHREAK", .text = "Hey, it's me."},
{.character = "KATE", .text = "Phreak?"},
{.character = "PHREAK", .text = "I'm freaking! Joey wasn't making it up! He really hacked into Ellingson! He gave me the disc with a file he copied and now I'm in jail! They're charging me with some serious shit! And there's stuff I didn't even do, like inserting some virus called Da Vinci, and they keep asking about you guys."},
{.character = "KATE", .text = "You think they're going to bust us?"},
{.character = "PHREAK", .text = "Yeah! You better figure out what's on that disc, cause we're being framed. It's in that place where I put that thing that time?"},
{.character = "MRS. MURPHY", .text = "Hi! Well, now I see what all the fuss is about. Dade... you have company."},
{.character = "CEREAL", .text = "It's a nice room."},
{.character = "KATE", .text = "We need your help."},
{.character = "DADE", .text = "Do my ears deceive me?"},
{.character = "CEREAL", .text = "Nonononono. Truce, you guys. Listen, we got a higher purpose here, alright? A wake up call for the Nintendo Generation. We demand free access to data, well, it comes with some responsibility. When I was a child, I spake as a child, I understood as a child, I thought as a child, but when I became a man I put away childish things. What... It's Corinthians I, Chapter 13, verse 11, no duh. Come on."},
{.character = "KATE", .text = "Phreak and Joey are being framed. We need your help to figure out what's on this disc."},
{.character = "DADE", .text = "I can't. Everybody who touches that thing gets busted, I can't afford to get arrested, I'm sorry."},
{.character = "CEREAL", .text = "Maybe I should just go to the bathroom or something."},
{.character = "KATE", .text = "What is it with you? I know we've been playing games, but, we're supposed to be on the same side and we really need your help. I really need your help."},
{.character = "DADE", .text = "I'm sorry, I can't."},
{.character = "KATE", .text = "Well, could you just make a copy of the disc? And just hide it in case we get busted, so we have something to give our lawyers, something that hasn't been tampered with? Can you do that?"},
{.character = "MRS. MURPHY", .text = "Listen you guys, help yourself to anything in the fridge. Cereal has."},
{.character = "KATE", .text = "Thank you."},
{.character = "DADE", .text = "Okay. I'll copy it."},
{.character = "KATE", .text = "Okay, thank you."},
{.character = "PLAGUE", .text = "The girl. The girl has the disc I need."},
{.character = "DADE", .text = "I told you, I don't play well with others."},
{.character = "PLAGUE", .text = "Turn on your laptop. Set it to receive a file."},
{.character = "PLAGUE", .text = "Lauren Murphy is now a wanted felon in the state of Washington. Forgery, Embezzlement, two drug convictions, plus she jumped parole. When she's arrested, she will not have a trial, she will not pass go, she will go directly to jail. Then I change this file back to the original, and your mom disappears."},
{.character = "DADE", .text = "That's bullshit."},
{.character = "PLAGUE", .text = "What can I tell you. Computers never lie, kid. Your mom will be arrested at work, she'll be handcuffed, and later, strip searched."},
{.character = "DADE", .text = "You lay a finger on her and I'll kill you."},
{.character = "PLAGUE", .text = "Kid, don't threaten me. There are worse things than death and, uh, I can do all of them!"},
{.character = "PLAGUE", .text = "Talk to me."},
{.character = "DADE", .text = "I got it. But listen, Kate didn't know what's on it. I mean, she came to me to figure it out. She's not the one who planted the virus. You leave her alone."},
{.character = "PLAGUE", .text = "Hey, don't worry, kid. If she's innocent, she'll be fine. Your mommy's safe now, okay?"},
{.character = "DADE", .text = "Kate, listen."},
{.character = "KATE", .text = "Uh, hold on..."},
{.character = "DADE", .text = "I have to tell you something."},
{.character = "CEREAL", .text = "Hold on a second!"},
{.character = "NIKON", .text = "Look at this, it's so lean and clean."},
{.character = "CEREAL", .text = "Looks like a hacker wrote it."},
{.character = "KATE", .text = "Come here, look at this. This thing is dense."},
{.character = "NIKON", .text = "But that's ill, man. It's incomplete. This is taking forever and a day to figure out. I'm gonna make some coffee."},
{.character = "CEREAL", .text = "Tag, you're in."},
{.character = "DADE", .text = "This isn't a virus. It's a worm!"},
{.character = "NIKON", .text = "What's this one eat?"},
{.character = "DADE", .text = "It nibbles. You see this?"},
{.character = "DADE", .text = "This is every financial transaction Ellingson conducts, yeah? From million dollar deals to the ten bucks some guy pays for gas."},
{.character = "KATE", .text = "The worm eats a few cents from each transaction."},
{.character = "DADE", .text = "And no one's caught it because the money isn't really gone. It's just data being shifted around."},
{.character = "KATE", .text = "Right. And when the worm's ready, it zips out with the money and erases its tracks."},
{.character = "DADE", .text = "Joey got cut off before he got to that part. Check it out. By this point, it's already running at, what, twice the speed as when it started."},
{.character = "KATE", .text = "Right, and at this rate it ends its run in..."},
{.character = "NIKON", .text = "Two days."},
{.character = "DADE", .text = "And judging by this segment alone, it's already eaten about..."},
{.character = "CEREAL", .text = "21.8 million bucks, man."},
{.character = "KATE", .text = "Whoever wrote this needs somebody to take the fall. And that's Phreak, and that's Joey, and that's us. We've got to get the rest of the file, so we can find out where the money is going before the worm disappears, so we can find out WHO created it."},
{.character = "DADE", .text = "I know, I know who wrote it."},
{.character = "KATE", .text = "What?"},
{.character = "DADE", .text = "This Ellingson security creep. I gave him a copy of the disc you gave me."},
{.character = "KATE", .text = "You what?"},
{.character = "DADE", .text = "I didn't know what was on it."},
{.character = "CEREAL", .text = "Oh man. That's universally stupid, man!"},
{.character = "NIKON", .text = "Yo, man, you an amateur, man."},
{.character = "KATE", .text = "Why did he come to you?"},
{.character = "DADE", .text = "I got a record. I was Zero Cool."},
{.character = "NIKON", .text = "Zero Cool? Crashed fifteen hundred and seven systems in one day?"},
{.character = "NIKON", .text = "Biggest crash in history, front page, New York Times, August 10th, 1988. I thought you was black, man! Yo, man, this is Zero Cool! Oh, shit!"},
{.character = "CEREAL", .text = "That's far out!"},
{.character = "NIKON", .text = "This is Zero Cool, man! Whooo, haha!"},
{.character = "KATE", .text = "Well that's great. There goes MIT."},
{.character = "DADE", .text = "I'll make it up to you!"},
{.character = "KATE", .text = "How?"},
{.character = "DADE", .text = "I'll hack the Gibson."},
{.character = "NIKON", .text = "They'll trace you like that man, cops are gonna find you, they're gonna find you with a smoking gun."},
{.character = "DADE", .text = "Fucked if I care, man."},
{.character = "NIKON", .text = "Look, even if you had the passwords, it'll take you ten minutes to get in, and you've still gotta find the files, man, I mean, the cops will have you in... five minutes."},
{.character = "CEREAL", .text = "Oh wow, we are fried."},
{.character = "KATE", .text = "Never send a boy to do a woman's job. With me, we can do it in seven."},
{.character = "CEREAL", .text = "You're both screwed. I help, we can do it in six."},
{.character = "NIKON", .text = "Jesus, I gotta save all your asses. I help, we can do it in five minutes, man."},
{.character = "DADE", .text = "Okay. Let's go shopping."},
{.character = "CEREAL", .text = "Woo hoo! Boom!"},
{.character = "DADE", .text = "You know, if I didn't live by a strict code of honor, I might take advantage of this situation.  Erotically, as it were."},
{.character = "GUARD", .text = "Alright, hold it right there!"},
{.character = "DADE", .text = "Shit!!"},
{.character = "KATE", .text = "It's my subway defense system."},
{.character = "NIKON", .text = "He's way down there."},
{.character = "CEREAL", .text = "Ta-da!"},
{.character = "NIKON", .text = "Yo, brain dead, the manual!"},
{.character = "PHONE COMPANY TECH", .text = "Hey!"},
{.character = "CEREAL AND NIKON", .text = "TRUCK!!!"},
{.character = "WOMAN", .text = "Find it?"},
{.character = "CEREAL", .text = "Phone's alright. The problem must be somewhere else."},
{.character = "MARGO", .text = "They had a large chunk of the garbage file? How much do they know?"},
{.character = "PLAGUE", .text = "Not everything. But enough to implicate us."},
{.character = "MARGO", .text = "You said the worm was untreaceable!"},
{.character = "PLAGUE", .text = "Yeah. To civilians. But they're hackers. But don't worry. All we have to do is launch the Da Vinci virus, and then they'll all be put away."},
{.character = "MARGO", .text = "Launch the Da Vinci virus? You can't do that!"},
{.character = "PLAGUE", .text = "No one believes the guilty. Besides, by the time they realize the truth, we'll be long gone with all of our money."},
{.character = "PLAGUE", .text = "Look, there is no right and wrong.  There is only fun and boring. A thirty year prison sentence sounds pretty dull to me.  Who do you prefer serves it, us? Or them?"},
{.character = "VIRUS", .text = "Unless five million dollars are transferred to the following numbered account in seven days, I will capsize five tankers in the Ellingson fleet."},
{.character = "PLAGUE", .text = "The virus goes off tomorrow morning at 10:30, and those hackers tried to get into our system again. At this point I insist you take more strenuous action, or Ellingson Mineral will hold the Secret Service responsible."},
{.character = "GILL", .text = "Get me arrest warrants on Kate Libby, alias Acid Burn, Emmanuel Goldstein, alias Cereal Killer, Dade Murphy, alias Crash Override, also known as Zero Cool, and Paul Cook, alias Lord Nikon. We pick them up tomorrow morning at nine o'clock."},
{.character = "CEREAL", .text = "Snoop onto them..."},
{.character = "NIKON", .text = "...as they snoop onto us."},
{.character = "KATE", .text = "Yeah, it's Kate."},
{.character = "NIKON", .text = "Hey, Burn. We got a little problem here."},
{.character = "KATE", .text = "Alright, so what have we got?"},
{.character = "DADE", .text = "Well, we have fifty passwords, plus whatever Polaroid head here got inside Ellingson."},
{.character = "NIKON", .text = "Well, I got a lot, alright? I don't know how many but... my head hurts."},
{.character = "CEREAL", .text = "Yo, everyone check this out. Hey, what's the Da Vinci virus?"},
{.character = "DADE", .text = "What?"},
{.character = "CEREAL", .text = "Check this out. It's a memo about how they're gonna deal with those oil spills that happened on the fourteenth."},
{.character = "KATE", .text = "What oil spills?"},
{.character = "NIKON", .text = "Whoa, whoa. Yo, brain-dead, today is the thirteenth."},
{.character = "CEREAL", .text = "Well this hasn't happened yet."},
{.character = "KATE", .text = "Wait a minute, the fourteenth, that's the same day the worm ends its run.  I mean... Da Vinci virus, didn't Phreak say that's what he was being charged with? Look... \"Infecting ballast programs of Ellingson tankers\" - they blame hackers!"},
{.character = "NIKON", .text = "Damn!"},
{.character = "CEREAL", .text = "A worm AND a virus? The plot thickens."},
{.character = "NIKON", .text = "Whoa, whoa whoa whoa, where are you going, huh?"},
{.character = "KATE", .text = "I got an idea. We've got a few hours, right, till we get arrested. So just stay low. I'm gonna go get some help. I'll beep you, okay? Are you coming?"},
{.character = "CEREAL", .text = "May the Force be with you, man."},
{.character = "KATE", .text = "There they are!"},
{.character = "DADE", .text = "Razor and Blade! They're flakes!"},
{.character = "KATE", .text = "They're elite! Let's get 'em."},
{.character = "KATE", .text = "I lost 'em. Where were you?"},
{.character = "DADE", .text = "I don't like this."},
{.character = "DADE", .text = "AAAAAUGH! I definitely don't like this!"},
{.character = "BLADE", .text = "What do you want?"},
{.character = "DADE", .text = "Ummm... we come in peace?"},
{.character = "KATE", .text = "We need your help.  If you're up to it."},
{.character = "RAZOR", .text = "She's buff. Ballsy."},
{.character = "BLADE", .text = "Let's keep her."},
{.character = "RAZOR", .text = "Waste the dude."},
{.character = "KATE", .text = "A virus called Da Vinci will cause oil spills at 10:30 AM Eastern Time tomorrow."},
{.character = "DADE", .text = "It's somehow connected with the worm that's stealing the money."},
{.character = "KATE", .text = "We need your help to overload the Gibson so we can kill the Da Vinci virus and download the worm program."},
{.character = "RAZOR", .text = "She's rabid, but cute."},
{.character = "BLADE", .text = "See, we're very busy. A TV network that wishes to remain nameless has expressed an interest in our show."},
{.character = "DADE", .text = "Let's go, Kate."},
{.character = "RAZOR", .text = "Wait. Nobody said no. But you are going to need more than just two media icons like us. You need an army."},
{.character = "BLADE", .text = "That's it! An electronic army! If I were us, I'd get on the internet, send out a major distress signal."},
{.character = "RAZOR", .text = "Hackers of the World, Unite!"},
{.character = "BLADE", .text = "How are you going to take care of the cops?"},
{.character = "CEREAL", .text = "Yo. I'm blowing up. It's Kate, Grand Central. Let's hit it!"},
{.character = "CEREAL", .text = "Hey Joey, you made it!"},
{.character = "KATE", .text = "Now listen up, use your best viruses to buy us time, we have to get into Plague's file and copy the worm."},
{.character = "CEREAL", .text = "Ai! Boom boom aiaiaiaiaee! Alright, that was a little tension breaker, that had to be done, alright?"},
{.character = "KATE", .text = "Cereal."},
{.character = "CEREAL", .text = "Yeah?"},
{.character = "KATE", .text = "Go fix the phones."},
{.character = "CEREAL", .text = "Roger."},
{.character = "KATE", .text = "Joey, take his place."},
{.character = "JOEY", .text = "What, me?"},
{.character = "KATE", .text = "Take his place, man, do it. You can do it."},
{.character = "KATE", .text = "Ready?"},
{.character = "DADE", .text = "Yeah."},
{.character = "KATE", .text = "Alright, let's boot up."},
{.character = "MARGO", .text = "What is it? What's wrong?"},
{.character = "PLAGUE", .text = "Nothing, it's just a minor glitch."},
{.character = "MARGO", .text = "\"Minor glitch\" with you seems to turn into a major catastrophe."},
{.character = "HAL", .text = "There's a new virus in the database."},
{.character = "MARGO", .text = "What's happening?"},
{.character = "HAL", .text = "It's replicating, eating up memory. What do I do?"},
{.character = "PLAGUE", .text = "Type \"Cookie\", you idiot. I'll head 'em off at the pass."},
{.character = "HAL", .text = "We have a Zero Bug attacking all the login and overlay files."},
{.character = "PLAGUE", .text = "Run anti-virus. Give me a systems display!"},
{.character = "PLAGUE", .text = "Die, dickweeds!"},
{.character = "HAL", .text = "The rabbit is in the administration system."},
{.character = "PLAGUE", .text = "Send a Flu-shot."},
{.character = "MARGO", .text = "Rabbit, Flu-shot, someone talk to me."},
{.character = "HAL", .text = "A rabbit replicates till it overloads a file, then it spreads like cancer."},
{.character = "MARGO", .text = "Cancer?"},
{.character = "KATE", .text = "It's the Gibson, it's finding us too fast."},
{.character = "DADE", .text = "Man, there's too many garbage files, I need more time."},
{.character = "PLAGUE", .text = "They're at Grand Central Station, lower level. Don't screw up."},
{.character = "PLAGUE", .text = "Game's over. Last chance to get out of this without a prison sentence.  You're not good enough to beat me, you little shit."},
{.character = "DADE", .text = "Yeah, maybe I'm not. But we are, you asshole."},
{.character = "PLAGUE", .text = "Give it up! Just give it up."},
{.character = "RAZOR", .text = "Are we fashionably late?"},
{.character = "SYSOP", .text = "We have massive infection.  Multiple GPI and FSI viruses."},
{.character = "HAL", .text = "They're coming in from remote nodes. They're going after the Kernal!"},
{.character = "MARGO", .text = "Colonel who?"},
{.character = "HAL", .text = "The System Command Processor, it's the brain."},
{.character = "MARGO", .text = "Cancer, brain... Brain Cancer?"},
{.character = "DUKE ELLINGSON", .text = "Belford, what's going on?"},
{.character = "PLAGUE", .text = "In short, Duke, a shit storm."},
{.character = "DADE", .text = "I found it! I found it!"},
{.character = "PLAGUE", .text = "This is the end, my friend. Thank you for calling!"},
{.character = "DADE", .text = "Oh, shit! He got me."},
{.character = "NIKON", .text = "Joey's getting stupid busy."},
{.character = "DADE", .text = "Joey. I need you to drop your viruses, go after the worm. You're the closest."},
{.character = "DADE", .text = "It's root slash period workspace slash period garbage period."},
{.character = "GILL", .text = "Freeze!"},
{.character = "GILL", .text = "Ahhh Come on!"},
{.character = "KATE", .text = "Kill the Gibson."},
{.character = "RAZOR", .text = "Roger that."},
{.character = "PLAGUE", .text = "Come on you son of a bitch, is that all you got, huh? Come on, let's see what else you can do! You talking to me? Huh? Hahahaha. Are you nuts? Come at me!"},
{.character = "HAL", .text = "They're in the kernal."},
{.character = "DA VINCI VIRUS", .text = "Help... me..."},
{.character = "WOMAN", .text = "The tankers have stopped capsizing."},
{.character = "SOMEONE ELSE", .text = "Ballast tanks are emptying. It'll be okay."},
{.character = "PLAGUE", .text = "Little pissant!"},
{.character = "NIKON", .text = "Yes!"},
{.character = "DADE", .text = "We did it!"},
{.character = "KATE", .text = "Let's get out of here!"},
{.character = "GILL", .text = "FREEZE!"},
{.character = "DADE", .text = "They're TRASHING our rights, man! They're TRASHING the flow of data! They're TRASHING! TRASHING! TRASHING! HACK THE PLANET! HACK THE PLANET!"},
{.character = "GILL", .text = "Shut up and get in the car!"},
{.character = "CEREAL", .text = "HACK THE PLANET! HACK THE PLANET!"},
{.character = "PLAGUE", .text = "Hello?"},
{.character = "GILL", .text = "We caught 'em."},
{.character = "PLAGUE", .text = "Good."},
{.character = "GILL", .text = "Red handed! You won't be having any more trouble from them."},
{.character = "DADE", .text = "Me, alright? I did it. She knows shit about computers. She... she's just my girlfriend."},
{.character = "GILL", .text = "I suggest you modify your attitude. Because you are floating. And I'm about to flush your ass."},
{.character = "AGENT", .text = "You've got a Mrs. Murphy to see you, sir."},
{.character = "KATE", .text = "Are you crazy? What are you doing?"},
{.character = "DADE", .text = "I'm trying to help you."},
{.character = "KATE", .text = "Dade."},
{.character = "DADE", .text = "What?"},
{.character = "KATE", .text = "Thanks for your help."},
{.character = "GILL", .text = "Your son is in big trouble. He has violated his probation and he has engaged in criminal activity."},
{.character = "MRS. MURPHY", .text = "My son happens to be a genius. He understands something happening today that you won't comprehend if you live to be a hundred, and he would never use what he knows to harm a living soul."},
{.character = "AGENT BOB", .text = "The news crew you requested is here."},
{.character = "MRS. MURPHY", .text = "Oh good. Cause I have a few things to tell them."},
{.character = "GILL", .text = "Your son is facing thirty felony counts in an ongoing investigation. You face possible arrest if you do that."},
{.character = "MRS. MURPHY", .text = "Mister, I don't care if I face certain death."},
{.character = "GILL", .text = "Mrs. Murphy stays right here."},
{.character = "KATE", .text = "Oh, wow, she's great."},
{.character = "DADE", .text = "Yeah."},
{.character = "REPORTER", .text = "...and attacked the Ellingson's computer network. Is the last we've seen of this type of high-tech espionage?"},
{.character = "GILL", .text = "Well, I'm afraid not. Hackers are a grave threat to the national security. This incident just proves without a doubt that we need increased funding to stop..."},
{.character = "SOMEONE", .text = "That kid cut him off!"},
{.character = "CEREAL", .text = "Hold on, boys and girls. It is I, the Cereal Killer, making my first coast to coast, world wide, global television appearance. Yes, that's right, I'm here to tell you about this heinous scheme hatched from within Ellingson Mineral."},
{.character = "CEREAL", .text = "But for what, you ask? World domination? Nay. Something far more tacky. A virus called Da Vinci, that when launched, would cause Ellingson Mineral tankers to capsize was to be blamed on innocent hackers. But this virus was really the smokescreen, right. What could be so vitally important to protect that someone would create such a nasty, antisocial, very uncool virus program?"},
{.character = "CEREAL", .text = "But why? Could it be to cover the tracks for this worm program? A worm that was to steal 25 million bucks. The password for this hungry little sucker belongs to Margo Wallace, head of public relations at Ellingson Mineral..."},
{.character = "MARGO", .text = "Oh my God!"},
{.character = "CEREAL", .text = "...and Eugene Belford, Computer Security Officer."},
{.character = "GILL", .text = "Son of a BITCH!"},
{.character = "CEREAL", .text = "What's this? Is this the unnamed account in the Bahamas where the money was to be stashed? I think so!"},
{.character = "CEREAL", .text = "Yo. I kinda feel like God!"},
{.character = "MARGO", .text = "Plague? Eugene?"},
{.character = "MARGO", .text = "I don't even know how to work a VCR, let alone a computer! Get off! Look, listen, I'll make a deal. Eugene Belford! I know where his mother is, I promise you. Get offa me! I need a lawyer!"},
{.character = "STEWARDESS", .text = "Here you are, Mr. Babbage.  Flight time to Tokyo should be about 14 hours today. Can I get you anything else?"},
{.character = "PLAGUE", .text = "Just a pillow please."},
{.character = "PLAGUE", .text = "Thank you."},
{.character = "GILL", .text = "You're welcome."},
{.character = "PLAGUE", .text = "What's going on? Let go of me! Stewardess! I'll never fly this airline again!"},
{.character = "DADE", .text = "You look good in a dress."},
{.character = "KATE", .text = "You would have looked better."},
{.character = "DADE", .text = "Wanna go for a swim?"},
{.character = "KATE", .text = "I can't believe they decided you won."},
{.character = "DADE", .text = "They didn't. The guys felt it was the only way I'd get a date. Anyway, you're pretty good. You're elite."},
{.character = "KATE", .text = "Yeah? You know if you would have said so in the beginning, you would have saved yourself a whole lot of trouble."},
{.character = "DADE", .text = "Beat that!"},
{.character = "DADE", .text = "You know, I've been having these really weird.."},
{.character = "KATE", .text = "Dreams?"},
